version: '3.9'

services:
  m2m:
    platform: linux/arm64
    container_name: m2m
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "sleep infinity"
    volumes:
      - ./:/app
    network_mode: host

